In [1]:
import sys

print(sys.executable)

c:\Users\Lenovo\venv\python.exe

In [2]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 2.3.3
NumPy version: 1.26.4

In [3]:
customers = pd.read_csv("../data/raw/olist_customers_dataset.csv")

customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [4]:
print("Rows:", customers.shape[0])
print("Columns:", customers.shape[1])

Rows: 99441
Columns: 5

In [5]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [6]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [ ]:
#uniqueness and duplicate customers

print("Unique customer_id:", customers["customer_id"].nunique())
print("Unique customer_unique_id:", customers["customer_unique_id"].nunique())

Unique customer_id: 99441
Unique customer_unique_id: 96096

In [ ]:
#find repeat customers
customer_order_counts = customers["customer_unique_id"].value_counts()

customer_order_counts.head(10)

customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    17
3e43e6105506432c953e165fb2acf44c     9
1b6c7548a2a1f9037c1fd3ddfed95f33     7
ca77025e7201e3b30c44b472ff346268     7
6469f99c1f9dfae7733b25662e7f1782     7
63cfc61cee11cbe306bff5857d00bfe4     6
47c1a3033b8b77b3ab6e109eb4d5fdf3     6
12f5d6e1cbf93dafd9dcc19095df0b3d     6
de34b16117594161a6a89c50b289d35a     6
dc813062e0fc23409cd255f7f53c7074     6
Name: count, dtype: int64

In [ ]:
#Count actual repeat customers

repeat_customers = (customer_order_counts > 1).sum()

print("Repeat customers:", repeat_customers)

Repeat customers: 2997

In [ ]:
#repeat-customer rate

repeat_customer_rate = repeat_customers / customers["customer_unique_id"].nunique() * 100

print("Repeat customer rate:", round(repeat_customer_rate, 2), "%")

Repeat customer rate: 3.12 %

In [11]:
orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")

orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [12]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [13]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [ ]:
#missing counts to percentages
missing_percentage = orders.isnull().mean() * 100

print(missing_percentage.round(2))

order_id                         0.00
customer_id                      0.00
order_status                     0.00
order_purchase_timestamp         0.00
order_approved_at                0.16
order_delivered_carrier_date     1.79
order_delivered_customer_date    2.98
order_estimated_delivery_date    0.00
dtype: float64

In [15]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [ ]:
#missing delivery dates by order status
pd.crosstab(
    orders["order_status"],
    orders["order_delivered_customer_date"].isnull()
)

order_delivered_customer_date  False  True
order_status
approved                           0      2
canceled                           6    619
created                            0      5
delivered                      96470      8
invoiced                           0    314
processing                         0    301
shipped                            0   1107
unavailable                        0    609

In [17]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

In [18]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [20]:
#dataset time period
print("First order:", orders["order_purchase_timestamp"].min())
print("Last order:", orders["order_purchase_timestamp"].max())

First order: 2016-09-04 21:15:19
Last order: 2018-10-17 17:30:18

In [22]:
#order volume by month

orders_by_month = (
    orders
    .set_index("order_purchase_timestamp")
    .resample("ME")
    .size()
)

orders_by_month

order_purchase_timestamp
2016-09-30       4
2016-10-31     324
2016-11-30       0
2016-12-31       1
2017-01-31     800
2017-02-28    1780
2017-03-31    2682
2017-04-30    2404
2017-05-31    3700
2017-06-30    3245
2017-07-31    4026
2017-08-31    4331
2017-09-30    4285
2017-10-31    4631
2017-11-30    7544
2017-12-31    5673
2018-01-31    7269
2018-02-28    6728
2018-03-31    7211
2018-04-30    6939
2018-05-31    6873
2018-06-30    6167
2018-07-31    6292
2018-08-31    6512
2018-09-30      16
2018-10-31       4
Freq: ME, dtype: int64

In [ ]:
#how many orders are truly unique

print("Total rows:", len(orders))
print("Unique order IDs:", orders["order_id"].nunique())

Total rows: 99441
Unique order IDs: 99441

In [ ]:
#customer_id uniqueness in orders

print("Unique customer IDs in orders:", orders["customer_id"].nunique())

Unique customer IDs in orders: 99441

In [ ]:
#Join orders with customers

orders_customers = orders.merge(
    customers,
    on="customer_id",
    how="left"
)

orders_customers.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

In [26]:
print("Orders rows:", len(orders))
print("Joined rows:", len(orders_customers))

Orders rows: 99441
Joined rows: 99441

In [27]:
orders_customers["customer_unique_id"].isnull().sum()

0

In [ ]:
#calculate repeat buyers using the joined data

orders_per_customer = (orders_customers.groupby("customer_unique_id")["order_id"].nunique())
orders_per_customer.head()

customer_unique_id
0000366f3b9a7992bf8c76cfdf3221e2    1
0000b849f77a49e4a4ce2b2a4ca5be3f    1
0000f46a3911fa3c0805444483337064    1
0000f6ccb0745a6a4b88665a16c9f078    1
0004aac84e0df4da2b147fca70cf8255    1
Name: order_id, dtype: int64

In [ ]:
#Count repeat buyers properly

repeat_buyers = (orders_per_customer > 1).sum()

total_customers = orders_per_customer.size

repeat_buyer_rate = repeat_buyers / total_customers * 100

print("Total unique customers:", total_customers)
print("Repeat buyers:", repeat_buyers)
print("Repeat buyer rate:", round(repeat_buyer_rate, 2), "%")

Total unique customers: 96096
Repeat buyers: 2997
Repeat buyer rate: 3.12 %

In [30]:
orders_per_customer.value_counts().sort_index()

order_id
1     93099
2      2745
3       203
4        30
5         8
6         6
7         3
9         1
17        1
Name: count, dtype: int64

In [31]:
order_items = pd.read_csv("../data/raw/olist_order_items_dataset.csv")

order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [32]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [33]:
print("Total item rows:", len(order_items))
print("Unique orders:", order_items["order_id"].nunique())

Total item rows: 112650
Unique orders: 98666

In [ ]:
#Compare orders vs order items

orders_without_items = orders[~orders["order_id"].isin(order_items["order_id"])]

orders_without_items["order_status"].value_counts()

order_status
unavailable    603
canceled       164
created          5
invoiced         2
shipped          1
Name: count, dtype: int64

In [ ]:
#Calculate basket size

items_per_order = order_items.groupby("order_id")["order_item_id"].count()

print("Average items per order:", round(items_per_order.mean(), 2))
print("Maximum items in one order:", items_per_order.max())

Average items per order: 1.14
Maximum items in one order: 21

In [36]:
items_per_order.value_counts().sort_index()

order_item_id
1     88863
2      7516
3      1322
4       505
5       204
6       198
7        22
8         8
9         3
10        8
11        4
12        5
13        1
14        2
15        2
20        2
21        1
Name: count, dtype: int64

In [ ]:
#single-item order percentage

single_item_orders = (items_per_order == 1).sum()

single_item_rate = single_item_orders / len(items_per_order) * 100

print("Single-item orders:", single_item_orders)
print("Single-item order rate:", round(single_item_rate, 2), "%")

Single-item orders: 88863
Single-item order rate: 90.06 %

In [38]:
order_items["price"].describe()

count    112650.000000
mean        120.653739
std         183.633928
min           0.850000
25%          39.900000
50%          74.990000
75%         134.900000
max        6735.000000
Name: price, dtype: float64

In [ ]:
#most expensive items

order_items.nlargest(10, "price")[["order_id", "product_id", "price", "freight_value"]]

,order_id,product_id,price,freight_value
3556,0812eb902a67711a1cb742b3cdaa65ae,489ae2aa008f021502940f251d4cce7f,6735.00,194.31
112233,fefacc66af859508bf1a7934eab1e97f,69c590f7ffc7bf8db97190b6cb6ed62e,6729.00,193.21
107841,f5136e38d1a14a4dbd87dff67da82701,1bdf5e6731585cf01aa8169c7028d6ad,6499.00,227.66
74336,a96610ab360d42a2e5335a3998b4718a,a6492cc69376c469ab6f61d8f44de961,4799.00,151.34
11249,199af31afc78c699f0dbf71fb178d4d4,c3ed642d592594bb648ff4a04cee2747,4690.00,74.34
62086,8dbc85d1447242f3b127dda390d56e19,259037a6a41845e455183f89c5035f18,4590.00,91.78
29193,426a9742b533fc6fed17d1fd6d143d7e,a1beef8f3992dbd4cd8726796aa69c53,4399.87,113.45
45843,68101694e5c5dc7330c91e1bbc36214f,6cdf8fc1d741c76586d8b6b15e9eef30,4099.99,75.27
78310,b239ca7cd485940b31882363b52e6674,dd113cb02b2af9c8e5787e8f1f0722f6,4059.00,104.51
59137,86c4eab1571921a6a6e248ed312f5a5a,6902c1962dd19d540807d0ab8fade5c6,3999.90,17.01

In [41]:
products = pd.read_csv("../data/raw/olist_products_dataset.csv")

products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [42]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [43]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [44]:
descriptive_cols = [
    "product_category_name",
    "product_name_lenght",
    "product_description_lenght",
    "product_photos_qty"
]

products[descriptive_cols].isnull().all(axis=1).sum()

610

In [ ]:
#Identify the expensive products

top_expensive = (order_items.nlargest(10, "price")
    .merge(
        products,
        on="product_id",
        how="left"
    )
)

top_expensive[["product_id", "product_category_name", "price", "freight_value"]]

,product_id,product_category_name,price,freight_value
0,489ae2aa008f021502940f251d4cce7f,utilidades_domesticas,6735.00,194.31
1,69c590f7ffc7bf8db97190b6cb6ed62e,pcs,6729.00,193.21
2,1bdf5e6731585cf01aa8169c7028d6ad,artes,6499.00,227.66
3,a6492cc69376c469ab6f61d8f44de961,eletroportateis,4799.00,151.34
4,c3ed642d592594bb648ff4a04cee2747,eletroportateis,4690.00,74.34
5,259037a6a41845e455183f89c5035f18,pcs,4590.00,91.78
6,a1beef8f3992dbd4cd8726796aa69c53,instrumentos_musicais,4399.87,113.45
7,6cdf8fc1d741c76586d8b6b15e9eef30,consoles_games,4099.99,75.27
8,dd113cb02b2af9c8e5787e8f1f0722f6,esporte_lazer,4059.00,104.51
9,6902c1962dd19d540807d0ab8fade5c6,relogios_presentes,3999.90,17.01

In [47]:
category_translation = pd.read_csv(
    "../data/raw/product_category_name_translation.csv"
)

category_translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [ ]:
#Add English category names to products

products_en = products.merge(
    category_translation,
    on="product_category_name",
    how="left"
)

products_en.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares

In [ ]:
#Check whether any valid category failed to translate

missing_translations = products_en[products_en["product_category_name"].notna()
& products_en["product_category_name_english"].isna()]

print("Products with category but no English translation:", len(missing_translations))

Products with category but no English translation: 13

In [ ]:
missing_translations[["product_category_name", "product_category_name_english"]].drop_duplicates()

,product_category_name,product_category_name_english
1628,pc_gamer,NaN
5821,portateis_cozinha_e_preparadores_de_alimentos,NaN

In [51]:
missing_translations["product_category_name"].value_counts()

product_category_name
portateis_cozinha_e_preparadores_de_alimentos    10
pc_gamer                                          3
Name: count, dtype: int64

In [52]:
print("Total product rows:", len(products))
print("Unique product IDs:", products["product_id"].nunique())

Total product rows: 32951
Unique product IDs: 32951

In [53]:
payments = pd.read_csv("../data/raw/olist_order_payments_dataset.csv")

payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [54]:
payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [55]:
print("Total payment rows:", len(payments))
print("Unique orders in payments:", payments["order_id"].nunique())

Total payment rows: 103886
Unique orders in payments: 99440

In [56]:
payments_per_order = payments.groupby("order_id").size()

multi_payment_orders = (payments_per_order > 1).sum()

print("Orders with multiple payment records:", multi_payment_orders)
print("Maximum payment records for one order:", payments_per_order.max())

Orders with multiple payment records: 2961
Maximum payment records for one order: 29

In [58]:
orders_without_payment = orders[~orders["order_id"].isin(payments["order_id"])]

orders_without_payment[["order_id", "order_status", "order_purchase_timestamp"]]

                               order_id order_status order_purchase_timestamp
30710  bfbd0f9bdef84302105ad712db648a6c    delivered      2016-09-15 12:16:38

In [59]:
payments["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [60]:
payments[payments["payment_type"] == "not_defined"]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0

In [61]:
undefined_payment_orders = payments[payments["payment_type"] == "not_defined"][["order_id"]]

undefined_payment_orders.merge(
    orders[["order_id", "order_status"]],
    on="order_id",
    how="left"
)

                           order_id order_status
0  4637ca194b6387e2d538dc89b124b0ee     canceled
1  00b1cb0320190ca0daa2c88b35206009     canceled
2  c8c528189310eaa44a745b8d9d26908b     canceled

In [62]:
payments["payment_installments"].value_counts().sort_index()

payment_installments
0         2
1     52546
2     12413
3     10461
4      7098
5      5239
6      3920
7      1626
8      4268
9       644
10     5328
11       23
12      133
13       16
14       15
15       74
16        5
17        8
18       27
20       17
21        3
22        1
23        1
24       18
Name: count, dtype: int64

In [63]:
payments[payments["payment_installments"] == 0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [64]:
zero_installment_order_ids = payments.loc[payments["payment_installments"] == 0,"order_id"]

payments[payments["order_id"].isin(zero_installment_order_ids)].sort_values(["order_id", "payment_sequential"])

,order_id,payment_sequential,payment_type,payment_installments,payment_value
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69

In [65]:
orders[orders["order_id"].isin(zero_installment_order_ids)][["order_id", "order_status", "order_purchase_timestamp"]]

                               order_id order_status order_purchase_timestamp
63782  744bade1fcf9ff3f31d860ace076d422    delivered      2018-04-22 11:34:42
66368  1a57108394169c0b47d8f876acc9ba2d    delivered      2018-05-15 16:25:14

In [66]:
payments["payment_value"].describe()

count    103886.000000
mean        154.100380
std         217.494064
min           0.000000
25%          56.790000
50%         100.000000
75%         171.837500
max       13664.080000
Name: payment_value, dtype: float64

In [67]:
zero_payments = payments[payments["payment_value"] == 0]

print("Zero-value payment records:", len(zero_payments))

zero_payments["payment_type"].value_counts()

Zero-value payment records: 9

payment_type
voucher        6
not_defined    3
Name: count, dtype: int64

In [68]:
zero_vouchers = payments[(payments["payment_value"] == 0) &(payments["payment_type"] == "voucher")]

zero_vouchers

,order_id,payment_sequential,payment_type,payment_installments,payment_value
19922,8bcbe01d44d147f901cd3192671144db,4,voucher,1,0.0
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.0
43744,6ccb433e00daae1283ccc956189c82ae,4,voucher,1,0.0
62674,45ed6e85398a87c253db47c2d9f48216,3,voucher,1,0.0
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.0
100766,b23878b3e8eb4d25a158f57d96331b18,4,voucher,1,0.0

In [70]:
zero_voucher_order_ids = zero_vouchers["order_id"].unique()

payments[payments["order_id"].isin(zero_voucher_order_ids)].sort_values(["order_id", "payment_sequential"])

,order_id,payment_sequential,payment_type,payment_installments,payment_value
33781,45ed6e85398a87c253db47c2d9f48216,1,voucher,1,21.13
11755,45ed6e85398a87c253db47c2d9f48216,2,voucher,1,50.01
62674,45ed6e85398a87c253db47c2d9f48216,3,voucher,1,0.00
40546,6ccb433e00daae1283ccc956189c82ae,1,credit_card,5,84.67
93478,6ccb433e00daae1283ccc956189c82ae,2,voucher,1,14.65
92318,6ccb433e00daae1283ccc956189c82ae,3,voucher,1,22.72
43744,6ccb433e00daae1283ccc956189c82ae,4,voucher,1,0.00
20963,8bcbe01d44d147f901cd3192671144db,1,credit_card,1,36.21
63762,8bcbe01d44d147f901cd3192671144db,2,voucher,1,31.70
5163,8bcbe01d44d147f901cd3192671144db,3,voucher,1,6.25
19922,8bcbe01d44d147f901cd3192671144db,4,voucher,1,0.00
44891,b23878b3e8eb4d25a158f57d96331b18,1,credit_card,1,35.98
55494,b23878b3e8eb4d25a158f57d96331b18,2,voucher,1,122.79
72011,b23878b3e8eb4d25a158f57d96331b18,3,voucher,1,12.80
100766,b23878b3e8eb4d25a158f57d96331b18,4,voucher,1,0.00
14321,fa65dad1b0e818e3ccc5cb0e39231352,1,voucher,1,3.71
23074,fa65dad1b0e818e3ccc5cb0e39231352,2,voucher,1,8.51
65641,fa65dad1b0e818e3ccc5cb0e39231352,3,voucher,1,2.95
9985,fa65dad1b0e818e3ccc5cb0e39231352,4,voucher,1,29.16
28330,fa65dad1b0e818e3ccc5cb0e39231352,5,voucher,1,0.66
29648,fa65dad1b0e818e3ccc5cb0e39231352,6,voucher,1,5.02
82593,fa65dad1b0e818e3ccc5cb0e39231352,7,voucher,1,0.32
68853,fa65dad1b0e818e3ccc5cb0e39231352,8,voucher,1,26.02
17274,fa65dad1b0e818e3ccc5cb0e39231352,9,voucher,1,1.08
19565,fa65dad1b0e818e3ccc5cb0e39231352,10,voucher,1,12.86
32519,fa65dad1b0e818e3ccc5cb0e39231352,11,voucher,1,4.03
73537,fa65dad1b0e818e3ccc5cb0e39231352,12,voucher,1,3.60
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.00
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.00
63369,fa65dad1b0e818e3ccc5cb0e39231352,15,voucher,1,14.04
78050,fa65dad1b0e818e3ccc5cb0e39231352,16,voucher,1,12.86
79670,fa65dad1b0e818e3ccc5cb0e39231352,17,voucher,1,3.72
80321,fa65dad1b0e818e3ccc5cb0e39231352,18,voucher,1,0.73
74721,fa65dad1b0e818e3ccc5cb0e39231352,19,voucher,1,5.02
93337,fa65dad1b0e818e3ccc5cb0e39231352,20,voucher,1,150.00
74239,fa65dad1b0e818e3ccc5cb0e39231352,21,voucher,1,4.11
100606,fa65dad1b0e818e3ccc5cb0e39231352,22,voucher,1,4.03
85166,fa65dad1b0e818e3ccc5cb0e39231352,23,voucher,1,18.86
99213,fa65dad1b0e818e3ccc5cb0e39231352,24,voucher,1,0.42
24879,fa65dad1b0e818e3ccc5cb0e39231352,25,voucher,1,3.68
79587,fa65dad1b0e818e3ccc5cb0e39231352,26,voucher,1,28.27
4885,fa65dad1b0e818e3ccc5cb0e39231352,27,voucher,1,66.02
39111,fa65dad1b0e818e3ccc5cb0e39231352,28,voucher,1,29.05
39108,fa65dad1b0e818e3ccc5cb0e39231352,29,voucher,1,19.26

In [71]:
order_payment_totals = (payments.groupby("order_id", as_index=False)["payment_value"].sum())

order_payment_totals.head()

                           order_id  payment_value
0  00010242fe8c5a6d1ba2dd792cb16214          72.19
1  00018f77f2f0320c557190d7a144bdd3         259.83
2  000229ec398224ef6ca0657da4fc703e         216.87
3  00024acbcdf0a6daa1e931b038114c75          25.78
4  00042b26cf59d7ce69dfabb4e55b4fd9         218.04

In [72]:
print("Rows in aggregated payment table:", len(order_payment_totals))
print("Unique order IDs:", order_payment_totals["order_id"].nunique())

Rows in aggregated payment table: 99440
Unique order IDs: 99440

In [74]:
order_item_totals = (order_items.assign(item_total=order_items["price"] + order_items["freight_value"])
    .groupby("order_id", as_index=False)["item_total"].sum())

order_item_totals.head()

                           order_id  item_total
0  00010242fe8c5a6d1ba2dd792cb16214       72.19
1  00018f77f2f0320c557190d7a144bdd3      259.83
2  000229ec398224ef6ca0657da4fc703e      216.87
3  00024acbcdf0a6daa1e931b038114c75       25.78
4  00042b26cf59d7ce69dfabb4e55b4fd9      218.04

In [75]:
payment_check = order_item_totals.merge(
    order_payment_totals,
    on="order_id",
    how="inner"
)

payment_check["difference"] = (payment_check["payment_value"] - payment_check["item_total"])

payment_check.head()

                           order_id  item_total  payment_value    difference
0  00010242fe8c5a6d1ba2dd792cb16214       72.19          72.19  0.000000e+00
1  00018f77f2f0320c557190d7a144bdd3      259.83         259.83  0.000000e+00
2  000229ec398224ef6ca0657da4fc703e      216.87         216.87  0.000000e+00
3  00024acbcdf0a6daa1e931b038114c75       25.78          25.78  0.000000e+00
4  00042b26cf59d7ce69dfabb4e55b4fd9      218.04         218.04 -2.842171e-14

In [76]:
mismatched_orders = payment_check[payment_check["difference"].abs() > 0.01]

print("Orders with payment mismatch:", len(mismatched_orders))

Orders with payment mismatch: 378

In [77]:
mismatched_orders["difference"].describe()

count    378.000000
mean       7.594788
std       16.616332
min      -51.620000
25%        0.010000
50%        3.155000
75%        9.667500
max      182.810000
Name: difference, dtype: float64

In [79]:
mismatched_orders[["order_id", "item_total", "payment_value", "difference"]].sort_values("difference",key=abs,
ascending=False
).head(10)

                               order_id  item_total  payment_value  difference
79537  ce6d150fb29ada17d2082f4847107665     1403.66        1586.47      182.81
42515  6e5fe7366a2e1bfbf3257dba0af1267f      287.91         406.92      119.01
43434  70b742795bc441e94a44a084b6d9ce7a      466.93         578.82      111.89
58752  996c7e73600ad3723e8627ab7bef81e4      587.90         664.43       76.53
43437  70b7e94ea46d3e8b5bc12a50186edaf0      213.15         274.84       61.69
72496  bc2c82b0ef78d2252b6176d1972db7c9      242.01         303.02       61.01
67466  af9ffff2ce6b3defd34fd4c78857a379      413.17         466.97       53.80
14628  262118ce178bb3e4590a3adcf6d62e6b      177.74         126.12      -51.62
73899  bfdb5bbb06458d600a33d61f5f287472      348.93         394.36       45.43
54305  8d9c0dc8d5a2ce804f6b925d8f8e6c1d      254.45         293.89       39.44

In [80]:
order_id_check = "ce6d150fb29ada17d2082f4847107665"

print("ORDER ITEMS")
display(order_items[order_items["order_id"] == order_id_check])

print("PAYMENTS")
display(payments[payments["order_id"] == order_id_check])

ORDER ITEMS

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
90875,ce6d150fb29ada17d2082f4847107665,1,638bbb2a5e4f360b71f332ddfebfd672,c4af86330efa7a2620772227d2d670c9,2018-02-07 12:31:37,1299.0,104.66

PAYMENTS

,order_id,payment_sequential,payment_type,payment_installments,payment_value
359,ce6d150fb29ada17d2082f4847107665,1,credit_card,10,1586.47

In [81]:
order_installments = (payments.groupby("order_id", as_index=False)["payment_installments"].max())

payment_check_with_installments = payment_check.merge(order_installments,on="order_id",how="left")

payment_check_with_installments[payment_check_with_installments["difference"].abs() > 0.01
]["payment_installments"].value_counts().sort_index()

payment_installments
1     66
2     23
3     48
4     48
5     33
6     36
7     18
8     19
9      9
10    53
11     4
12    15
13     1
15     2
20     1
21     1
24     1
Name: count, dtype: int64

In [83]:
payment_check_with_installments["is_mismatch"] = (payment_check_with_installments["difference"].abs() > 0.01)

mismatch_rate_by_installment = (payment_check_with_installments.groupby("payment_installments")["is_mismatch"]
.agg(["count", "sum", "mean"])
)

mismatch_rate_by_installment["mean"] *= 100

mismatch_rate_by_installment

                      count  sum       mean
payment_installments
0                         2    0   0.000000
1                     47823   66   0.138009
2                     12291   23   0.187129
3                     10371   48   0.462829
4                      7022   48   0.683566
5                      5188   33   0.636083
6                      3887   36   0.926164
7                      1611   18   1.117318
8                      4237   19   0.448430
9                       635    9   1.417323
10                     5261   53   1.007413
11                       22    4  18.181818
12                      131   15  11.450382
13                       16    1   6.250000
14                       15    0   0.000000
15                       74    2   2.702703
16                        5    0   0.000000
17                        7    0   0.000000
18                       27    0   0.000000
20                       17    1   5.882353
21                        3    1  33.333333
22                        1    0   0.000000
23                        1    0   0.000000
24                       18    1   5.555556

In [84]:
mismatch_order_ids = mismatched_orders["order_id"]

mismatch_payment_types = payments[payments["order_id"].isin(mismatch_order_ids)]["payment_type"].value_counts()

mismatch_payment_types

payment_type
credit_card    350
boleto          29
voucher         10
debit_card       9
Name: count, dtype: int64

In [85]:
total_orders_by_payment_type = (payments.groupby("payment_type")["order_id"].nunique())

mismatch_orders_by_payment_type = (payments[payments["order_id"].isin(mismatch_order_ids)].groupby("payment_type")["order_id"]
    .nunique())

payment_type_mismatch_rate = (mismatch_orders_by_payment_type/ total_orders_by_payment_type* 100)

payment_type_mismatch_rate.round(2)

payment_type
boleto         0.15
credit_card    0.44
debit_card     0.59
not_defined     NaN
voucher        0.26
Name: order_id, dtype: float64

In [86]:
mismatch_status = (orders[orders["order_id"].isin(mismatch_order_ids)]["order_status"].value_counts())

mismatch_status

order_status
delivered    372
shipped        3
canceled       2
invoiced       1
Name: count, dtype: int64

In [87]:
positive_mismatch = (mismatched_orders["difference"] > 0).sum()
negative_mismatch = (mismatched_orders["difference"] < 0).sum()

print("Payment greater than item total:", positive_mismatch)
print("Payment less than item total:", negative_mismatch)

Payment greater than item total: 290
Payment less than item total: 88

In [88]:
payment_record_counts = (payments.groupby("order_id").size())

mismatched_payment_counts = payment_record_counts[payment_record_counts.index.isin(mismatch_order_ids)]

print("Mismatch orders with one payment record:",(mismatched_payment_counts == 1).sum())

print("Mismatch orders with multiple payment records:",(mismatched_payment_counts > 1).sum())

Mismatch orders with one payment record: 358
Mismatch orders with multiple payment records: 20

In [89]:
items_count_per_order = (order_items.groupby("order_id").size())

mismatch_item_counts = items_count_per_order[items_count_per_order.index.isin(mismatch_order_ids)]

print("Mismatch orders with 1 item:",(mismatch_item_counts == 1).sum())

print("Mismatch orders with multiple items:",(mismatch_item_counts > 1).sum())

Mismatch orders with 1 item: 236
Mismatch orders with multiple items: 142

In [91]:
basket_type = pd.DataFrame({"item_count": items_count_per_order})

basket_type["basket_group"] = basket_type["item_count"].apply(lambda x: "single_item" if x == 1 else "multi_item")

basket_type["is_mismatch"] = basket_type.index.isin(mismatch_order_ids)

basket_type.groupby("basket_group")["is_mismatch"].agg(["count", "sum", "mean"])

              count  sum      mean
basket_group
multi_item     9803  142  0.014485
single_item   88863  236  0.002656

In [92]:
sellers_per_order = (order_items.groupby("order_id")["seller_id"].nunique())

sellers_per_order.value_counts().sort_index()

seller_id
1    97388
2     1219
3       54
4        3
5        2
Name: count, dtype: int64

In [93]:
seller_check = pd.DataFrame({"seller_count": sellers_per_order})

seller_check["is_mismatch"] = seller_check.index.isin(mismatch_order_ids)

seller_check.groupby("seller_count")["is_mismatch"].agg(["count", "sum", "mean"])

              count  sum      mean
seller_count
1             97388  338  0.003471
2              1219   38  0.031173
3                54    2  0.037037
4                 3    0  0.000000
5                 2    0  0.000000

In [94]:
seller_check["seller_group"] = seller_check["seller_count"].apply(lambda x: "single_seller" if x == 1 else "multi_seller")

seller_check.groupby("seller_group")["is_mismatch"].agg(["count", "sum", "mean"])

               count  sum      mean
seller_group
multi_seller    1278   40  0.031299
single_seller  97388  338  0.003471

In [95]:
combined_check = pd.DataFrame({"item_count": items_count_per_order,"seller_count": sellers_per_order})

combined_check["is_mismatch"] = combined_check.index.isin(mismatch_order_ids)

combined_check = combined_check[combined_check["item_count"] > 1].copy()

combined_check["seller_group"] = combined_check["seller_count"].apply(lambda x: "single_seller" if x == 1 else "multi_seller")

combined_check.groupby("seller_group")["is_mismatch"].agg(["count", "sum", "mean"])

               count  sum      mean
seller_group
multi_seller    1278   40  0.031299
single_seller   8525  102  0.011965

In [96]:
reviews = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")

reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [97]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [98]:
print("Total review rows:", len(reviews))
print("Unique review IDs:", reviews["review_id"].nunique())
print("Unique order IDs:", reviews["order_id"].nunique())

Total review rows: 99224
Unique review IDs: 98410
Unique order IDs: 98673

In [99]:
review_id_counts = reviews["review_id"].value_counts()

print("Review IDs appearing more than once:",(review_id_counts > 1).sum())

print("Maximum rows for one review ID:",review_id_counts.max())

Review IDs appearing more than once: 789
Maximum rows for one review ID: 3

In [100]:
repeated_review_id = review_id_counts[review_id_counts > 1].index[0]

reviews[reviews["review_id"] == repeated_review_id].sort_values("review_answer_timestamp")

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
7500,7b606b0d57b078384f0b58eac1d41d78,f3028a8f41ea1ee2b461420913663f97,5,NaN,NaN,2017-02-15 00:00:00,2017-02-21 23:30:22
59859,7b606b0d57b078384f0b58eac1d41d78,2deb17060fc1ce18a85eba953ddcdeaf,5,NaN,NaN,2017-02-15 00:00:00,2017-02-21 23:30:22
61069,7b606b0d57b078384f0b58eac1d41d78,2f8f31eb2f7b6572836d662a6625c8e4,5,NaN,NaN,2017-02-15 00:00:00,2017-02-21 23:30:22

In [102]:
duplicate_review_order_pairs = reviews.duplicated(subset=["review_id", "order_id"]).sum()

print("Duplicate review_id + order_id pairs:",duplicate_review_order_pairs)

Duplicate review_id + order_id pairs: 0

In [103]:
reviews_per_order = reviews["order_id"].value_counts()

print("Orders with more than one review:",(reviews_per_order > 1).sum())

print("Maximum review rows for one order:",reviews_per_order.max())

Orders with more than one review: 547
Maximum review rows for one order: 3

In [104]:
multi_review_order = reviews_per_order[reviews_per_order > 1].index[0]

reviews[reviews["order_id"] == multi_review_order].sort_values("review_answer_timestamp")

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
82525,202b5f44d09cd3cfc0d6bd12f01b044c,c88b1d1b157a9999ce368f218a407141,5,NaN,NaN,2017-07-22 00:00:00,2017-07-26 13:40:22
1985,ffb8cff872a625632ac983eb1f88843c,c88b1d1b157a9999ce368f218a407141,3,NaN,NaN,2017-07-22 00:00:00,2017-07-26 13:41:07
89360,fb96ea2ef8cce1c888f4d45c8e22b793,c88b1d1b157a9999ce368f218a407141,5,NaN,NaN,2017-07-21 00:00:00,2017-07-26 13:45:15

In [105]:
scores_per_order = (reviews.groupby("order_id")["review_score"].nunique())

conflicting_score_orders = (scores_per_order > 1).sum()

print("Orders with conflicting review scores:", conflicting_score_orders)

Orders with conflicting review scores: 202

In [106]:
multi_review_orders_count = (reviews_per_order > 1).sum()

conflict_rate = (conflicting_score_orders/ multi_review_orders_count* 100)

print("Conflict rate among multi-review orders:", round(conflict_rate, 2), "%")

Conflict rate among multi-review orders: 36.93 %

In [107]:
reviews["review_creation_date"] = pd.to_datetime(reviews["review_creation_date"])

reviews["review_answer_timestamp"] = pd.to_datetime(reviews["review_answer_timestamp"])

In [108]:
reviews_sorted = reviews.sort_values(["order_id", "review_answer_timestamp"])

In [109]:
latest_reviews = reviews_sorted.drop_duplicates(subset="order_id",keep="last")

print("Rows in latest review table:", len(latest_reviews))
print("Unique orders:", latest_reviews["order_id"].nunique())

Rows in latest review table: 98673
Unique orders: 98673

In [111]:
first_reviews = (reviews_sorted.drop_duplicates(subset="order_id", keep="first")[["order_id", "review_score"]]
.rename(columns={"review_score": "first_score"})
)

last_reviews = (latest_reviews[["order_id", "review_score"]].rename(columns={"review_score": "latest_score"}))

review_score_change = first_reviews.merge(last_reviews,on="order_id",how="inner")

review_score_change["score_changed"] = (review_score_change["first_score"]!= review_score_change["latest_score"])

print("Orders where first and latest review scores differ:",review_score_change["score_changed"].sum())

Orders where first and latest review scores differ: 201

In [112]:
changed_reviews = review_score_change[review_score_change["score_changed"]].copy()

changed_reviews["change"] = (changed_reviews["latest_score"]- changed_reviews["first_score"])

print("Improved score:", (changed_reviews["change"] > 0).sum())
print("Lower score:", (changed_reviews["change"] < 0).sum())

Improved score: 88
Lower score: 113

In [ ]:
#review-score distribution
latest_reviews["review_score"].value_counts().sort_index()

review_score
1    11363
2     3131
3     8133
4    19038
5    57008
Name: count, dtype: int64

In [114]:
#average review score

average_review_score = latest_reviews["review_score"].mean()

print("Average review score:", round(average_review_score, 2))

Average review score: 4.09

In [ ]:
#Calculating low-rating rate

low_rating_rate = (latest_reviews["review_score"].isin([1, 2]).mean() * 100)

print("Low-rating rate:", round(low_rating_rate, 2), "%")

Low-rating rate: 14.69 %

In [117]:
#whether late delivery affects ratings

review_delivery = latest_reviews.merge(
    orders[["order_id","order_delivered_customer_date","order_estimated_delivery_date"]],
    on="order_id",
    how="left"
)

review_delivery.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,order_delivered_customer_date,order_estimated_delivery_date
0,97ca439bc427b48bc1cd7177abe71365,00010242fe8c5a6d1ba2dd792cb16214,5,NaN,"Perfeito, produto entregue antes do combinado.",2017-09-21,2017-09-22 10:57:03,2017-09-20 23:43:48,2017-09-29
1,7b07bacd811c4117b742569b04ce3580,00018f77f2f0320c557190d7a144bdd3,4,NaN,NaN,2017-05-13,2017-05-15 11:34:13,2017-05-12 16:04:24,2017-05-15
2,0c5b33dea94867d1ac402749e5438e8b,000229ec398224ef6ca0657da4fc703e,5,NaN,Chegou antes do prazo previsto e o produto sur...,2018-01-23,2018-01-23 16:06:31,2018-01-22 13:19:16,2018-02-05
3,f4028d019cb58564807486a6aaf33817,00024acbcdf0a6daa1e931b038114c75,4,NaN,NaN,2018-08-15,2018-08-15 16:39:01,2018-08-14 13:32:39,2018-08-20
4,940144190dcba6351888cafa43f3a3a5,00042b26cf59d7ce69dfabb4e55b4fd9,5,NaN,Gostei pois veio no prazo determinado .,2017-03-02,2017-03-03 10:54:59,2017-03-01 16:42:31,2017-03-17

In [118]:
#Creating an is_late flag

review_delivery["is_late"] = (review_delivery["order_delivered_customer_date"]
                              >review_delivery["order_estimated_delivery_date"])

In [119]:
review_delivery["is_late"].value_counts()

is_late
False    91011
True      7662
Name: count, dtype: int64

In [120]:
# classify only orders that actually have a delivery date.

delivered_reviews = review_delivery[review_delivery["order_delivered_customer_date"].notna()].copy()

delivered_reviews["is_late"] = (delivered_reviews["order_delivered_customer_date"]
                                >delivered_reviews["order_estimated_delivery_date"])

delivered_reviews["is_late"].value_counts()

is_late
False    88168
True      7662
Name: count, dtype: int64

In [122]:
#Compare review score: late vs on-time

delivered_reviews.groupby("is_late")["review_score"].mean()

is_late
False    4.293973
True     2.565127
Name: review_score, dtype: float64

In [124]:
# Compare low-rating rates that is What percentage of on-time vs late orders receive a 1–2 star review

delivered_reviews["is_low_rating"] = (delivered_reviews["review_score"].isin([1, 2]))

delivered_reviews.groupby("is_late")["is_low_rating"].mean() * 100

is_late
False     9.225569
True     54.058992
Name: is_low_rating, dtype: float64

In [ ]:
#low-rating risk

low_rating_on_time = 9.225569
low_rating_late = 54.058992

relative_risk = low_rating_late / low_rating_on_time

print("Relative risk:", round(relative_risk, 2))

Relative risk: 5.86

In [126]:
# calculate directly from the DataFrame

low_rating_rates = (delivered_reviews.groupby("is_late")["is_low_rating"].mean())

relative_risk = (low_rating_rates[True]/ low_rating_rates[False])

print("Relative risk:", round(relative_risk, 2))

Relative risk: 5.86

In [127]:
# Calculating the overall late-delivery rate

late_delivery_rate = delivered_reviews["is_late"].mean() * 100

print("Late delivery rate:", round(late_delivery_rate, 2), "%")

Late delivery rate: 8.0 %

In [130]:
# how many days late

delivered_reviews["delay_days"] = (delivered_reviews["order_delivered_customer_date"]
                                   - delivered_reviews["order_estimated_delivery_date"]).dt.days




delivered_reviews.loc[delivered_reviews["is_late"],"delay_days"].describe()

count    7662.00000
mean        8.76142
std        13.76922
min         0.00000
25%         1.00000
50%         5.00000
75%        11.00000
max       188.00000
Name: delay_days, dtype: float64

In [131]:
# Correct the late-delivery definition: An order is late only if it arrives after the estimated delivery calendar date.

delivered_reviews["is_late"] = (delivered_reviews["order_delivered_customer_date"].dt.date
                                >delivered_reviews["order_estimated_delivery_date"].dt.date)

delivered_reviews["is_late"].value_counts()

is_late
False    89448
True      6382
Name: count, dtype: int64

In [132]:
# Recalculate the validated late-delivery metrics

late_delivery_rate = delivered_reviews["is_late"].mean() * 100

avg_rating_by_late = (delivered_reviews.groupby("is_late")["review_score"].mean())

low_rating_rate_by_late = (delivered_reviews.groupby("is_late")["is_low_rating"].mean() * 100)

print("Late delivery rate:", round(late_delivery_rate, 2), "%")

print("\nAverage rating:")
print(avg_rating_by_late.round(2))

print("\nLow-rating rate:")
print(low_rating_rate_by_late.round(2))

Late delivery rate: 6.66 %

Average rating:
is_late
False    4.29
True     2.27
Name: review_score, dtype: float64

Low-rating rate:
is_late
False     9.27
True     62.41
Name: is_low_rating, dtype: float64

In [133]:
# Recalculate delay days correctly

delivered_reviews["delay_days"] = (delivered_reviews["order_delivered_customer_date"].dt.normalize()
                                   -delivered_reviews["order_estimated_delivery_date"].dt.normalize()).dt.days

In [134]:
delivered_reviews.loc[delivered_reviews["is_late"],"delay_days"].describe()

count    6382.000000
mean       10.518646
std        14.461538
min         1.000000
25%         3.000000
50%         7.000000
75%        13.000000
max       188.000000
Name: delay_days, dtype: float64

In [135]:
#validated number of times more likely a late delivery is to receive a 1–2 star rating.

low_rating_rates = (delivered_reviews.groupby("is_late")["is_low_rating"].mean())

relative_risk = (low_rating_rates[True]/ low_rating_rates[False])

print("Relative risk:", round(relative_risk, 2))

Relative risk: 6.73

In [136]:
#longer delay lead to worse ratings?

late_reviews = delivered_reviews[delivered_reviews["is_late"]].copy()

late_reviews["delay_group"] = pd.cut(late_reviews["delay_days"],bins=[0, 3, 7, 14, 30, float("inf")],
    labels=[
        "1-3 days",
        "4-7 days",
        "8-14 days",
        "15-30 days",
        "30+ days"
    ]
)

late_reviews["delay_group"].value_counts().sort_index()

delay_group
1-3 days      1852
4-7 days      1748
8-14 days     1447
15-30 days    1006
30+ days       329
Name: count, dtype: int64

In [137]:
#Compare ratings across delay groups

delay_rating_summary = (late_reviews.groupby("delay_group", observed=False)
    .agg(orders=("order_id", "count"),average_rating=("review_score", "mean"),low_rating_rate=("is_low_rating", "mean")
         ))

delay_rating_summary["low_rating_rate"] *= 100

delay_rating_summary.round(2)

             orders  average_rating  low_rating_rate
delay_group
1-3 days       1852            3.29            32.13
4-7 days       1748            2.10            67.68
8-14 days      1447            1.67            80.10
15-30 days     1006            1.61            81.81
30+ days        329            2.06            67.78

In [138]:
#rating distribution for 30+ day delays

late_reviews[late_reviews["delay_group"] == "30+ days"]["review_score"].value_counts().sort_index()

review_score
1    208
2     15
3     30
4     31
5     45
Name: count, dtype: int64

In [139]:
#whether high-rated reviews happened before delivery

very_late_high_rating = late_reviews[(late_reviews["delay_group"] == "30+ days")& (late_reviews["review_score"] >= 4)
].copy()

very_late_high_rating["review_before_delivery"] = (very_late_high_rating["review_creation_date"]
                                                   <very_late_high_rating["order_delivered_customer_date"])

very_late_high_rating["review_before_delivery"].value_counts()

review_before_delivery
True    76
Name: count, dtype: int64

In [ ]:
#Checking how common this issue is overall

delivered_reviews["review_before_delivery"] = (delivered_reviews["review_creation_date"]
                                               <delivered_reviews["order_delivered_customer_date"])

print("Reviews created before delivery:",delivered_reviews["review_before_delivery"].sum())

print("Percentage:",round(delivered_reviews["review_before_delivery"].mean() * 100,2),"%")

Reviews created before delivery: 8141
Percentage: 8.5 %

In [141]:
# In this True means the review was created on an earlier calendar day than delivery, which is much more defensible.

delivered_reviews["review_before_delivery"] = (delivered_reviews["review_creation_date"].dt.date
                                               <delivered_reviews["order_delivered_customer_date"].dt.date)

print("Reviews created before delivery:",delivered_reviews["review_before_delivery"].sum())

print("Percentage:",round(delivered_reviews["review_before_delivery"].mean() * 100,2),"%")

Reviews created before delivery: 4977
Percentage: 5.19 %

In [142]:
#keeping only reviews created on or after the delivery date.

valid_delivery_reviews = delivered_reviews[~delivered_reviews["review_before_delivery"]].copy()

print("Valid delivered reviews:", len(valid_delivery_reviews))

Valid delivered reviews: 90853

In [143]:
#Recalculate the key delivery-impact metrics

summary = (valid_delivery_reviews.groupby("is_late")
    .agg(orders=("order_id", "count"),average_rating=("review_score", "mean"),low_rating_rate=("is_low_rating", "mean")
         ))

summary["low_rating_rate"] *= 100

summary.round(2)

         orders  average_rating  low_rating_rate
is_late
False     89223            4.29             9.25
True       1630            3.53            25.09

In [144]:
# Recalculate the clean relative risk

clean_low_rating_rates = (valid_delivery_reviews.groupby("is_late")["is_low_rating"].mean())

clean_relative_risk = (clean_low_rating_rates[True]/ clean_low_rating_rates[False])

print("Clean relative risk:",round(clean_relative_risk, 2))

Clean relative risk: 2.71

In [145]:
sellers = pd.read_csv("../data/raw/olist_sellers_dataset.csv")

sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [146]:
sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [148]:
#Validate the grain

print("Total seller rows:", len(sellers))
print("Unique seller IDs:", sellers["seller_id"].nunique())

Total seller rows: 3095
Unique seller IDs: 3095

In [ ]:
# Seller distribution by state

sellers["seller_state"].value_counts()

seller_state
SP    1849
PR     349
MG     244
SC     190
RJ     171
RS     129
GO      40
DF      30
ES      23
BA      19
CE      13
PE       9
PB       6
RN       5
MS       5
MT       4
RO       2
SE       2
PI       1
AC       1
MA       1
AM       1
PA       1
Name: count, dtype: int64

In [151]:
geolocation = pd.read_csv("../data/raw/olist_geolocation_dataset.csv")

geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [152]:
geolocation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [153]:
print("Unique ZIP prefixes:",geolocation["geolocation_zip_code_prefix"].nunique())

Unique ZIP prefixes: 19015

In [154]:
#how many rows each ZIP prefix has

geo_rows_per_zip = (geolocation["geolocation_zip_code_prefix"].value_counts())

geo_rows_per_zip.describe()

count    19015.000000
mean        52.598633
std         72.057907
min          1.000000
25%         10.000000
50%         29.000000
75%         66.500000
max       1146.000000
Name: count, dtype: float64

In [155]:
#Interpret the geolocation grain

geo_location_consistency = (geolocation.groupby("geolocation_zip_code_prefix")
    .agg(cities=("geolocation_city", "nunique"),states=("geolocation_state", "nunique")))

print("ZIP prefixes linked to multiple cities:",(geo_location_consistency["cities"] > 1).sum())

print("ZIP prefixes linked to multiple states:",(geo_location_consistency["states"] > 1).sum())

ZIP prefixes linked to multiple cities: 8556
ZIP prefixes linked to multiple states: 8

In [156]:
#ZIP-location consistency

multi_state_zips = geo_location_consistency[geo_location_consistency["states"] > 1].index

geolocation[geolocation["geolocation_zip_code_prefix"].isin(multi_state_zips)][[
        "geolocation_zip_code_prefix","geolocation_city","geolocation_state"]].drop_duplicates().sort_values(
    "geolocation_zip_code_prefix")

,geolocation_zip_code_prefix,geolocation_city,geolocation_state
21728,2116,sao paulo,SP
22193,2116,são paulo,SP
22261,2116,são paulo,RN
71032,4011,sao paulo,SP
71247,4011,são paulo,SP
72852,4011,sao paulo,AC
430342,21550,rio de janeiro,RJ
430999,21550,rio de janeiro,AC
460406,23056,rio de janeiro,AC
459234,23056,rio de janeiro,RJ
792362,72915,aguas lindas de goias,GO
792394,72915,taguatinga,DF
792490,72915,águas lindas de goiás,GO
825876,78557,sinop,MT
825882,78557,nova brasilandia d'oeste,RO
839731,79750,nova andradina,MS
840047,79750,nova andradina,RS
847184,80630,curitiba,PR
847700,80630,balneario de picarras,SC

In [157]:
#Creating one row per ZIP prefix

geo_summary = (geolocation.groupby("geolocation_zip_code_prefix", as_index=False)
    .agg(latitude=("geolocation_lat", "median"),longitude=("geolocation_lng", "median")))

geo_summary.head()

   geolocation_zip_code_prefix   latitude  longitude
0                         1001 -23.550381 -46.634027
1                         1002 -23.548551 -46.635072
2                         1003 -23.548977 -46.635313
3                         1004 -23.549535 -46.634771
4                         1005 -23.549612 -46.636532

In [158]:
# Adding the most common city and state

geo_city_state = (geolocation.groupby("geolocation_zip_code_prefix")
    .agg(city=("geolocation_city", lambda x: x.mode().iloc[0]),state=("geolocation_state", lambda x: x.mode().iloc[0]))
    .reset_index())

geo_city_state.head()

   geolocation_zip_code_prefix       city state
0                         1001  sao paulo    SP
1                         1002  sao paulo    SP
2                         1003  sao paulo    SP
3                         1004  sao paulo    SP
4                         1005  sao paulo    SP

In [159]:
# Combine  into one clean geolocation table

geo_clean = geo_summary.merge(geo_city_state,
    on="geolocation_zip_code_prefix",
    how="left")

geo_clean.head()

   geolocation_zip_code_prefix   latitude  longitude       city state
0                         1001 -23.550381 -46.634027  sao paulo    SP
1                         1002 -23.548551 -46.635072  sao paulo    SP
2                         1003 -23.548977 -46.635313  sao paulo    SP
3                         1004 -23.549535 -46.634771  sao paulo    SP
4                         1005 -23.549612 -46.636532  sao paulo    SP

In [161]:
print("Rows:", len(geo_clean))
print("Unique ZIP prefixes:",geo_clean["geolocation_zip_code_prefix"].nunique())

Rows: 19015
Unique ZIP prefixes: 19015

In [162]:
# geolocation coverage for customers

customer_geo_coverage = customers["customer_zip_code_prefix"].isin(geo_clean["geolocation_zip_code_prefix"])

print("Customers with geolocation match:",customer_geo_coverage.sum())

print("Customers without geolocation match:",(~customer_geo_coverage).sum())

Customers with geolocation match: 99163
Customers without geolocation match: 278

In [163]:
# geolocation coverage for sellers

seller_geo_coverage = sellers["seller_zip_code_prefix"].isin(geo_clean["geolocation_zip_code_prefix"])

print("Sellers with geolocation match:",seller_geo_coverage.sum())

print("Sellers without geolocation match:",(~seller_geo_coverage).sum())

Sellers with geolocation match: 3088
Sellers without geolocation match: 7